services:
  - type: web
    name: bhojanxpress
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: True
      - key: MAIL_USE_SSL
        value: False
      # Add these via Render dashboard (they contain sensitive data):
      # - DATABASE_URL (from your MySQL service)
      # - MAIL_USERNAME
      # - MAIL_PASSWORD
      # - MAIL_DEFAULT_SENDER
